/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as NoticiasImport } from './routes/noticias'
import { Route as IndexImport } from './routes/index'
import { Route as NoticiasIdImport } from './routes/noticias/$id'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const NoticiasRoute = NoticiasImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NoticiasIdRoute = NoticiasIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NoticiasRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/noticias/$id': {
      id: '/noticias/$id'
      path: '/$id'
      fullPath: '/noticias/$id'
      preLoaderRoute: typeof NoticiasIdImport
      parentRoute: typeof NoticiasImport
    }
  }
}

// Create and export the route tree

interface NoticiasRouteChildren {
  NoticiasIdRoute: typeof NoticiasIdRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasIdRoute: NoticiasIdRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/profile': typeof ProfileRoute
  '/noticias/$id': typeof NoticiasIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/profile': typeof ProfileRoute
  '/noticias/$id': typeof NoticiasIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/profile': typeof ProfileRoute
  '/noticias/$id': typeof NoticiasIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/noticias' | '/profile' | '/noticias/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/noticias' | '/profile' | '/noticias/$id'
  id: '__root__' | '/' | '/noticias' | '/profile' | '/noticias/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  ProfileRoute: typeof ProfileRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  ProfileRoute: ProfileRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/noticias",
        "/profile"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/noticias": {
      "filePath": "noticias.tsx",
      "children": [
        "/noticias/$id"
      ]
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/noticias/$id": {
      "filePath": "noticias/$id.tsx",
      "parent": "/noticias"
    }
  }
}
ROUTE_MANIFEST_END */
